<a href="https://colab.research.google.com/github/ERROR6447/learn_pytorch/blob/Learning/00_Learning_Module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#00 PyTorch Fundamentals

Resources for Exercise : https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot

In [ ]:
torch.__version__

'2.1.0+cu121'

## Introdcution to Tensors

Resource : https://pytorch.org/docs/stable/tensors.html

created using `torch.Tensor()`

It always create a copy of the tensor instead of using the existing one for example creating a tensor from numpy array will create another copy to not create the copy and use the existing one we need to use the function described in the documetation above

### Creating a Tensor

In [ ]:
### Scalar Tensor

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
## has no dimension
scalar.ndim

0

In [ ]:
# Get Tensor Back
scalar.item()

7

In [ ]:
# Vector has mangnititude and directions and head and tail
# has more than one number
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
# dimension number of rows present in the vecotr
print(vector.ndim)
# gives you the shape of the vector if only one row then will only show column else will show number of rows and couns
print(vector.shape)

1
torch.Size([2])


In [ ]:
vectors = torch.tensor([[7,7,7],[7,7,7]])

In [ ]:
# dimension number of rows present in the vecotr
print(vectors.ndim)
# number of column present in the vector
print(vectors.shape)

2
torch.Size([2, 3])


In [ ]:
## For tesnor of shape 1x1 returns not result set
print(scalar.shape)

torch.Size([])


In [ ]:
## MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
print(MATRIX.ndim)
print(MATRIX.shape)
print(MATRIX[0])
print(MATRIX[1][:])

2
torch.Size([2, 2])
tensor([7, 8])
tensor([ 9, 10])


In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,6,7],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 6, 7],
         [7, 8, 9]]])

In [ ]:
print(TENSOR.ndim)
print(TENSOR.shape)


3
torch.Size([1, 3, 3])


Summary :

a scalar and vector is often represented by a lower case \\
while the martix and tensor are represented by a upper case

### Creating a Random Tensor

These are important becuase most nerual network learning process starts with tensors full of random number and these numbers are adjusted as they learn to better represent the data. \\

`Start with random number - > look at data -> update random number -> look at the data -> update random number`
\\
continue till criteria for stopping is achieved \\
Resources: https://pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
##RANDOM Tensor
random_tensor = torch.rand (3,4)
random_tensor

tensor([[0.6953, 0.5127, 0.9175, 0.6683],
        [0.3396, 0.6634, 0.6006, 0.1950],
        [0.7233, 0.9942, 0.1960, 0.5551]])

In [ ]:
print(random_tensor.ndim)
print(random_tensor.shape)

2
torch.Size([3, 4])


In [ ]:
### Creating a random tensor with similar shape to an image tensor
### Sometimes the color channels comes first so 3,244,244 => color_channel,width,height
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, colour channels (R,G,B)
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and Ones

In [ ]:
### Creaitng a  tesnor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
 zeros.shape,random_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
### Creating Tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
## dtype is the type of the element of the datatype
ones.shape,ones.dtype

(torch.Size([3, 4]), torch.float32)

In [ ]:
ones_with_diff_dtype = torch.ones(size=(3,4),dtype=torch.int32)
ones_with_diff_dtype.shape,ones_with_diff_dtype.dtype

(torch.Size([3, 4]), torch.int32)

## Creating a range of Tensors and Tensors like

In [ ]:
# user torch.range()
torch.range(0,10)


<ipython-input-24-b8b6d4ee4e85>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
# create a range with start and end (Not Couting it ) and default step is 1
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# with change in step szie
torch.arange(start= 0,end = 15,step = 2)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14])

## For Creating a like tensor similar to other tensor
look for methods previsouly used for creating the tensor and those should have _like appended to them at the end of the function call

In [ ]:
## Cerating tensor like where we want shape as that of other tensor without explicitly specifying the shape of the tensor
zeros = torch.zeros(3,3)
like_the_above_tensor = torch.zeros_like(input=zeros)
like_the_above_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
zeros = torch.zeros(3,3)
like_the_above_tensor = torch.ones_like(input=zeros)
like_the_above_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
zeros = torch.zeros(3,3)
like_the_above_tensor = torch.rand_like(input=zeros)
like_the_above_tensor

tensor([[0.6029, 0.3426, 0.2302],
        [0.3444, 0.0615, 0.3130],
        [0.5566, 0.0247, 0.8032]])

## Tensor Data Types
Default data type for tensors is float32

**Note: ** Tensor datatypes is one of the 3 big error we'll run into with PyTorch and Deep Learning
1. Tensors are not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
none_data_type = torch.rand(size=(1,3),dtype=None)
none_data_type,none_data_type.dtype

(tensor([[0.2375, 0.8944, 0.8021]]), torch.float32)

In [ ]:
## Changing the data type of the tensor
none_data_type = torch.rand(size=(1,3),dtype=torch.float16)
none_data_type,none_data_type.dtype

(tensor([[0.2661, 0.6592, 0.1919]], dtype=torch.float16), torch.float16)

dtype: What datatype is the tensor \\
device: which device is your tensor on cpu or gpu \\
requires_grad: Whether or not to track gradients with this tensors operations \\

**Note:** rand function is only implemented to create float data type tensor

In [ ]:
###
none_data_type = torch.rand(size=(1,3),
                            dtype=None,  ## type of data of array elements
                            device=None,  ## by default it's 'CPU' when using gpu can write 'cuda'
                            requires_grad = False) ## When we want PyTorch to Watch Gradient when the tensor goes through numeric calculation
none_data_type,none_data_type.dtype

(tensor([[0.6772, 0.2447, 0.1697]]), torch.float32)

In [ ]:
## covnerting the data type of the tensors
float_16_tensor = none_data_type.type(torch.float16)
float_16_tensor, float_16_tensor.dtype

(tensor([[0.6772, 0.2446, 0.1697]], dtype=torch.float16), torch.float16)

In [ ]:
new_data_type = none_data_type * float_16_tensor
new_data_type, new_data_type.dtype

(tensor([[0.4586, 0.0599, 0.0288]]), torch.float32)

### Getting information from the tensor

1. dtype: get the type of the tensor
2. shape: get the shape of the tensor
3. device: get the device of the tensor
4. size() : can also use this function to get the size of the tensor

In [ ]:
### getting the information about the tensor can use tensor.dtype
new_tensor = torch.tensor([1,2,3,4,5],dtype=None)
new_tensor,new_tensor.dtype

(tensor([1, 2, 3, 4, 5]), torch.int64)

In [ ]:
### Getting the shape of the tensor we can  use tensor.shape
new_tensor.shape

torch.Size([5])

In [ ]:
### Getting the device on which the tensor exists we can use tensor.device
new_tensor.device

device(type='cpu')

In [ ]:
### Get the number of gpus present on the system
print(f'Number of GPUS available: {torch.cuda.device_count()}')
print('Can use this device using the function : torch.device(cuda:{which number of gpu we want to use starting from 0 to nubmer_of_gpu -1)')


Number of GPUS available: 0
Can use this device using the function : torch.device(cuda:{which number of gpu we want to use starting from 0 to nubmer_of_gpu -1)


In [ ]:
## creating a tensor with new type and change the device on which the tensor is on
new_test_tensor = torch.rand([1,2,3,4,5],dtype= torch.float16)
print(f'Device on which the tensor is on: {new_test_tensor.device}')
new_tensor_with_dff = new_test_tensor.to(dtype=torch.int32)
## Sample Code to change the device on which the tensor is on:
## new_tensor_with_dff = new_test_tensor.to(dtype=torch.int32,device=torch.device('cuda:0'))

new_tensor_with_dff.dtype

Device on which the tensor is on: cpu


torch.int32

## Manipulating Tensors (Tensor Operations )

Operations:
* Additon
* Multiplication (element wise (scalar multiplication) , matrix multiplication )
* Subtraction
* Division

Can See: matrixmultiplication.xyz for visualization

In [ ]:
## Addition
first_tensor = torch.tensor([1,2,3])
first_tensor + 10

tensor([11, 12, 13])

In [ ]:
## Subtraction
first_tensor = torch.tensor([1,2,3])
first_tensor - 10

tensor([-9, -8, -7])

In [ ]:
## Multiplication
first_tensor = torch.tensor([1,2,3])
first_tensor * 10

tensor([10, 20, 30])

In [ ]:
## Divison
first_tensor = torch.tensor([1,2,3])
first_tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
## Element wise multiplication in tensor Matrix
first_tensor = torch.tensor([1,2,3])
second_tensor = torch.tensor([[1],[2],[3]])
first_tensor * first_tensor

tensor([1, 4, 9])

In [ ]:
### Add the Result Set of the Multiplication Obtained Above
torch.matmul(first_tensor,first_tensor)

tensor(14)

In [ ]:
### @ stands for matrix multiplication
first_tensor @ first_tensor

tensor(14)

In [ ]:
## torch.mm is same as torch.matmul
## Note: torch.mm does not work for one dimensional matrix while torch.matmul works on one dimensional matrix
torch.mm(first_tensor,first_tensor)

RuntimeError: self must be a matrix

In [ ]:
## Performing Matrix Multiplication of the Tensor
first_tensor * second_tensor

tensor([[1, 2, 3],
        [2, 4, 6],
        [3, 6, 9]])

In [ ]:
### Pytorch in-built functions
torch.mul(first_tensor,10)

tensor([10, 20, 30])

In [ ]:
first_tensor = torch.tensor([[1, 3],
                            [2, 4],
                            [5, 6]])
second_tensor = torch.tensor([[7, 8],
                            [9, 10],
                            [11, 12]])
torch.mm(first_tensor,second_tensor)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
## torch.mm transpose one of the matrix so multiplication of 2 matrix which are of same type but are not square matrix results in error
## can  resolve this by transposing one of the matrix
first_tensor = torch.tensor([[1, 3],
                            [2, 4],
                            [5, 6]])
second_tensor = torch.tensor([[7, 8],
                            [9, 10],
                            [11, 12]])

print(f"Original Shape: first_tensor: {first_tensor.shape}, second_tensor: {second_tensor.shape}")
print(f"After Application of Transpose on Second Tensor: \n {second_tensor.T} \n And It's Shape: {second_tensor.T.shape}")
print(f"Dimension for Matrix multilicaiton: first_tensor: {first_tensor.shape}, Second Tesnor: {second_tensor.T.shape} ")
first_tensor,second_tensor,second_tensor.T,first_tensor.shape,second_tensor.shape,second_tensor.T.shape

Original Shape: first_tensor: torch.Size([3, 2]), second_tensor: torch.Size([3, 2])
After Application of Transpose on Second Tensor: 
 tensor([[ 7,  9, 11],
        [ 8, 10, 12]]) 
 And It's Shape: torch.Size([2, 3])
Dimension for Matrix multilicaiton: first_tensor: torch.Size([3, 2]), Second Tesnor: torch.Size([2, 3]) 


(tensor([[1, 3],
         [2, 4],
         [5, 6]]),
 tensor([[ 7,  8],
         [ 9, 10],
         [11, 12]]),
 tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([3, 2]),
 torch.Size([3, 2]),
 torch.Size([2, 3]))

In [ ]:
torch.mm(first_tensor,second_tensor.T)

tensor([[ 31,  39,  47],
        [ 46,  58,  70],
        [ 83, 105, 127]])

## Applying Aggregation Functions on Tensor

In [ ]:
x = torch.arange(0,1000,20)
### find the min
torch.min(x),x.min()

(tensor(0), tensor(0))

In [ ]:
### Find the max
torch.max(x),max(x)

(tensor(980), tensor(980))

In [ ]:
### Find the mean
### Note: Using the mean function can only find mean for datatype float, Complex data type  not int
x = x.to(dtype=torch.float32)
torch.mean(x),x.mean()

(tensor(490.), tensor(490.))

In [ ]:
torch.sum(x),x.sum()

(tensor(24500.), tensor(24500.))